package com.bank;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@Testcontainers
@SpringBootTest
class UserRepositoryIT {

    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres =
            new PostgreSQLContainer<>("postgres:15");

    @Autowired
    private UserRepository userRepository;

    @Test
    void testSaveUser() {

        // Create user
        User user = new User("Alice");

        // Save to PostgreSQL
        User savedUser = userRepository.save(user);

        // ID should be generated by PostgreSQL
        assertNotNull(savedUser.getId());

        // Fetch from PostgreSQL
        User foundUser = userRepository
                .findById(savedUser.getId())
                .orElseThrow();

        // Verify
        assertEquals("Alice", foundUser.getName());
    }
}