spring.application.name=bankingapp




# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingdb
spring.datasource.username=postgres
spring.datasource.password=pass123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Use Redis as Spring Cache provider
spring.cache.type=redis